### ISSUE TITLE
有没有专门搞的 GitHub Pages 的圈子

### ISSUE THREAD

**Issue by young1lin** [seognil/fe-foundation#4]
如题。
我感觉国内搞了 Github page 建站的，分享内容的，都挺多的，就是不知道有没有专门的电报群或者其他的群

**Comment by seognil** [comment]
没吧…我自己的话也就平时逛到随手star的（晚点再整理…）
其实知识体系的话也就那样，很多repo都差不多。
而深入的、硬核的专题，因为写的人少，一般还是要靠自己搜。

pages的话，其实只是形式之一，自己搭的也很多（我浏览器收藏夹里），像我就是vuepress+vercel部署的

**Comment by young1lin** [comment]
哦哦，就是有些人翻译了某些国外的文献，然后放到自己的 blog 网站上，然后难搜到。深入的、硬核的内容，比较难搜，全是 csdn 和 cnblogs 的，比较浅的内容，而且有可能还是实际上运行不起来的内容。

**Comment by young1lin** [comment]
对了，我看了你那个 Youtuber 推荐，我也看 Joma Tech，来搞笑的。最近终于更新了新的视频，不过没以前好玩了。我还关注了
`电玩科技AK`还有`大聪看电影`这种比较硬核的无关编程的 Youtuber，我比较推荐

**Comment by seognil** [comment]
这些我也有在看 油管频道我关注了也有百来个吧 本来之前那些有写的后来觉得无关就去掉了…

**Comment by young1lin** [comment]
我是觉得只要是优秀的 Youtuber 都值得被推荐
